apiVersion: v1
kind: Secret
metadata:
  name: hk-artifactory
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdG9yeS1oay5oYXJtYW4uY29tOjUwNDQiOnsidXNlcm5hbWUiOiJzdmNfYXVkaW1pYjMiLCJwYXNzd29yZCI6IlBFbSRcdTAwMjZBS2Ezb3ItNFJ1czUhVjgiLCJhdXRoIjoiYzNaalgyRjFaR2x0YVdJek9sQkZiU1FtUVV0aE0yOXlMVFJTZFhNMUlWWTQifX19